### ISSUE TITLE
执行报错

### ISSUE THREAD

**Issue by xianghongying** [starnightcyber/masnmap#2]
Kali和CentOS，Python 3.9和Python 3.11，均抛出如下错误：

# python3 masnmap.py
executing ==> sudo /usr/bin/masscan -iL ips.txt -p 1-65535 -oJ masscan.json --rate 1000
Starting masscan 1.3.2 (http://bit.ly/14GZzcT) at 2023-05-22 16:23:27 GMT
Initiating SYN Stealth Scan
Scanning 1 hosts [65535 ports/host]
117.50.183.34:6143                                                           
Traceback (most recent call last):
  File "/root/masnmap/masnmap.py", line 111, in <module>
    main()
  File "/root/masnmap/masnmap.py", line 100, in main
    extract_masscan()
  File "/root/masnmap/masnmap.py", line 44, in extract_masscan
    line_json = json.loads(tmp)
  File "/usr/local/python3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by starnightcyber** [comment]
hi  @xianghongying，
这个应该是由于 Masscan 版本 -oJ 参数输出的 json 文件格式内容不一致导致的。
你需要稍微调整 extract_masscan 中 json 文件解析。
参考第一条回复哈 ~
https://www.freebuf.com/sectool/257698.html
